### ISSUE TITLE
no effect but unspecified error when adding device

### ISSUE THREAD

**Issue by jubie25** [tizianodeg/gruenbeck_softliQ_SC#1]
If I want to add my SoftliQ as described I get this:
![grafik](https://github.com/user-attachments/assets/457cca10-01bb-4d07-8643-7a49db09133e)
pressing submit...
![grafik](https://github.com/user-attachments/assets/9ecd56a3-6776-4bcb-be4a-da4897845659)

Sorry not to have more infos. What can I do / provide you with more data?

**Comment by tizianodeg** [comment]
Hey, 
sure can you cross check you protocol in HA?
There you can see some details of the exception e.g. 
![image](https://github.com/user-attachments/assets/bd44eadb-0abe-4310-ac9b-89220f0bc953)

if it does not help you could provide some additional information:
- your softener model 
- if the mux interface is reachable http://10.9.0.2/mux_http
- make sure your gruenbeck app is not running, as the softener can only handle a few connection at the same time 
Best,
Tiziano

**Comment by jubie25** [comment]
Hi tizianodeg,

because of this
```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.gruenbeck_softliQ_SC.config_flow
Quelle: custom_components/gruenbeck_softliQ_SC/config_flow.py:54
Integration: Gruenbeck SoftliQ SC (Dokumentation)
Erstmals aufgetreten: 07:35:53 (1 Vorkommnisse)
Zuletzt protokolliert: 07:35:53

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1120, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1102, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1005, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.9.0.2', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/gruenbeck_softliQ_SC/config_flow.py", line 54, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/gruenbeck_softliQ_SC/config_flow.py", line 36, in validate_input
    muxClient = await SoftQLinkMuxClient.create(data[CONF_HOST], websession)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gruenbeck_softliQ_SC/softQLinkMuxClient.py", line 22, in create
    await client._init()
  File "/config/custom_components/gruenbeck_softliQ_SC/softQLinkMuxClient.py", line 37, in _init
    self.sw_version = await self.__getSoftwareVersion()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gruenbeck_softliQ_SC/softQLinkMuxClient.py", line 57, in __getSoftwareVersion
    result = await self._executeMuxQuery(props=[softwarecode])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gruenbeck_softliQ_SC/softQLinkMuxClient.py", line 110, in _executeMuxQuery
    async with self.session.post(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1033, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.9.0.2:80 ssl:default [Connect call failed ('10.9.0.2', 80)]
```
I tried to open port 80 of my softener IP address. But it is refused. There seems no ports open: 
```
nmap 10.9.0.2 -A
Starting Nmap 7.93 ( https://nmap.org ) at 2024-07-24 08:05 CEST
Nmap scan report for 10.9.0.2
Host is up (0.00033s latency).
All 1000 scanned ports on 10.9.0.2 are in ignored states.
Not shown: 1000 closed tcp ports (reset)
MAC Address: D8:86:0B:somestuff (Ieee Registration Authority)
Warning: OSScan results may be unreliable because we could not find at least 1 open and 1 closed port
Aggressive OS guesses: 2N Helios IP VoIP doorbell (95%), Advanced Illumination DCS-100E lighting controller (95%), AudioControl D3400 network amplifier (95%), British Gas GS-Z3 data logger (95%), Daysequerra M4.2SI radio (95%), Denver Electronics AC-5000W MK2 camera (95%), DTE Energy Bridge (lwIP stack) (95%), Enlogic PDU (FreeRTOS/lwIP) (95%), Espressif esp8266 firmware (lwIP stack) (95%), Espressif ESP8266 WiFi system-on-a-chip (95%)
No exact OS matches for host (test conditions non-ideal).
Network Distance: 1 hop
```
Is there a trick to get the device listening?
It's a softliQ:SD21 (Ethernet, Cloud active by now)

**Comment by tizianodeg** [comment]
OK sorry the local MUX interface that I am using here is not available for the SD devices...  It was removed instead they are using a cloud service to push data to. 

You can try to use this custom component, that connects to the cloud to get the data: 
https://github.com/p0l0/hagruenbeck_cloud
